on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build & Push - PHP8.2 Base Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-base:latest
          sbom: true
          provenance: true
          build-args: |
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Imagick Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-imagick:latest
          sbom: true
          provenance: true
          build-args: |
            "IMAGICK=true"
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Base MONGO Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-base-mongo:latest
          sbom: true
          provenance: true
          build-args: |
            "IMAGICK=true"
            "MONGO=true"
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Base Apache Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base-apache
          push: true
          tags: thekingscode/php8.2-base-apache:latest
          sbom: true
          provenance: true
          build-args: |
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Imagick Apache Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base-apache
          push: true
          tags: thekingscode/php8.2-imagick-apache:latest
          sbom: true
          provenance: true
          build-args: |
            "IMAGICK=true"
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Base Apache MONGO Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-apache-mongo:latest
          sbom: true
          provenance: true
          build-args: |
            "IMAGICK=true"
            "MONGO=true"
            "CLI=true"

      -
        name: Build & Push - PHP8.2 Base DEV Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-dev:latest
          sbom: true
          provenance: true
          build-args: |
            "DEVELOPMENT=true"
            "IMAGICK=true"

      -
        name: Build & Push - PHP8.2 Base MONGO DEV Image
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2/base
          push: true
          tags: thekingscode/php8.2-dev-mongo:latest
          sbom: true
          provenance: true
          build-args: |
            "DEVELOPMENT=true"
            "IMAGICK=true"
            "MONGO=true"