on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Latest Image and Get Digest
        id: digest
        run: |
          # Use the Docker Registry API to fetch the digest
          TAG_RESPONSE=$(curl -sSL "https://registry.hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG")

          # Extract the latest digest using jq
          # The digests are available under the 'images' array
          LATEST_DIGEST=$(echo "$TAG_RESPONSE" | jq -r '.images[0].digest')

          # Output the latest digest to GITHUB_OUTPUT
          echo "latest_digest=$LATEST_DIGEST" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2-apache-new
          push: true
          tags: thekingscode/php8.2-apache-new:latest
          sbom: true
          provenance: true
          build-args: |
            "PHP_DIGEST=${{ steps.digest.outputs.latest_digest }}"