on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.32.1/trivy_0.32.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.32.1_Linux-64bit.deb

      - name: Scan Image with Trivy
        run: |
          trivy image --severity CRITICAL,HIGH php:8.2

      - name: Get Digest of Pulled PHP 8.2 Image
        id: digest
        run: |
          # Get the latest digest of the pulled php:8.2 image
          LATEST_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' php:8.2 | cut -d'@' -f 2)
          echo "latest_digest=$LATEST_DIGEST" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2-apache-new
          push: true
          tags: thekingscode/php8.2-apache-new:latest
          sbom: true
          provenance: true
          build-args: |
            "PHP_DIGEST=${{ steps.digest.outputs.latest_digest }}"