on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push for production
        uses: docker/build-push-action@v3
        with:
          context: ./php8.1-nginx-alpine
          build-args: |
            development=false
          push: true
          tags: thekingscode/php8.1-nginx-alpine:latest
      -
        name: Build and push for development
        uses: docker/build-push-action@v3
        with:
          context: ./php8.1-nginx-alpine
          build-args: |
            development=true
          push: true
          tags: thekingscode/php8.1-nginx-alpine-dev:latest