on:
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull PHP 8.2 Image
        run: |
          docker pull php:8.2

      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: php:8.2
          severity: CRITICAL,HIGH

      - name: Get Digest of Pulled PHP 8.2 Image
        id: digest
        run: |
          # Ensure the image is pulled and retrieve its digest
          LATEST_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' php:8.2 | cut -d'@' -f 2)
          echo "latest_digest=$LATEST_DIGEST" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./php8.2-apache-new
          push: true
          tags: thekingscode/php8.2-apache-new:latest
          sbom: true
          provenance: true
          build-args: |
            "PHP_DIGEST=${{ steps.digest.outputs.latest_digest }}"